# 
senate_polls = [{u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'McConnell',
    u'first_name': u'Mitch',
    u'incumbent': True,
    u'last_name': u'McConnell',
    u'lead_confidence': 100.0,
    u'party': u'Rep',
    u'value': 50.1},
   {u'choice': u'Grimes',
    u'first_name': u'Alison Lundergan',
    u'incumbent': False,
    u'last_name': u'Grimes',
    u'lead_confidence': 0.0,
    u'party': u'Dem',
    u'value': 44.1}],
  u'last_updated': u'2014-11-02T14:37:22.000Z',
  u'poll_count': 57,
  u'short_title': u'2014 Kentucky Senate',
  u'slug': u'2014-kentucky-senate-mcconnell-vs-grimes',
  u'state': u'KY',
  u'title': u'2014 Kentucky Senate: McConnell vs. Grimes',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-kentucky-senate-mcconnell-vs-grimes'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Cotton',
    u'first_name': u'Tom',
    u'incumbent': False,
    u'last_name': u'Cotton',
    u'lead_confidence': 99.9,
    u'party': u'Rep',
    u'value': 51.7},
   {u'choice': u'Pryor',
    u'first_name': u'Mark',
    u'incumbent': True,
    u'last_name': u'Pryor',
    u'lead_confidence': 0.0,
    u'party': u'Dem',
    u'value': 45.6}],
  u'last_updated': u'2014-11-02T01:46:46.000Z',
  u'poll_count': 61,
  u'short_title': u'2014 Arkansas Senate',
  u'slug': u'2014-arkansas-senate-cotton-vs-pryor',
  u'state': u'AR',
  u'title': u'2014 Arkansas Senate: Cotton vs. Pryor',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-arkansas-senate-cotton-vs-pryor'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Peters',
    u'first_name': u'Gary',
    u'incumbent': False,
    u'last_name': u'Peters',
    u'lead_confidence': 100.0,
    u'party': u'Dem',
    u'value': 51.6},
   {u'choice': u'Land',
    u'first_name': u'Terri Lynn',
    u'incumbent': False,
    u'last_name': u'Land',
    u'lead_confidence': 0.0,
    u'party': u'Rep',
    u'value': 39.8}],
  u'last_updated': u'2014-11-04T03:11:39.000Z',
  u'poll_count': 67,
  u'short_title': u'2014 Michigan Senate',
  u'slug': u'2014-michigan-senate-land-vs-peters',
  u'state': u'MI',
  u'title': u'2014 Michigan Senate: Land vs. Peters',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-michigan-senate-land-vs-peters'},
 {u'election_date': u'2014-12-06',
  u'estimates': [{u'choice': u'Cassidy',
    u'first_name': u'Bill',
    u'incumbent': False,
    u'last_name': u'Cassidy',
    u'lead_confidence': 100.0,
    u'party': u'Rep',
    u'value': 55.5},
   {u'choice': u'Landrieu',
    u'first_name': u'Mary',
    u'incumbent': True,
    u'last_name': u'Landrieu',
    u'lead_confidence': 0.0,
    u'party': u'Dem',
    u'value': 42.3}],
  u'last_updated': u'2014-11-21T22:46:37.000Z',
  u'poll_count': 38,
  u'short_title': u'2014 Louisiana Senate',
  u'slug': u'2014-louisiana-senate-cassidy-vs-landrieu',
  u'state': u'LA',
  u'title': u'2014 Louisiana Senate: Cassidy vs. Landrieu',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-louisiana-senate-cassidy-vs-landrieu'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Shaheen',
    u'first_name': u'Jeanne',
    u'incumbent': True,
    u'last_name': u'Shaheen',
    u'lead_confidence': 89.6,
    u'party': u'Dem',
    u'value': 47.6},
   {u'choice': u'Brown',
    u'first_name': u'Scott',
    u'incumbent': False,
    u'last_name': u'Brown',
    u'lead_confidence': 10.4,
    u'party': u'Rep',
    u'value': 46.2}],
  u'last_updated': u'2014-11-04T01:55:05.000Z',
  u'poll_count': 62,
  u'short_title': u'2014 New Hampshire Senate',
  u'slug': u'2014-new-hampshire-senate-brown-vs-shaheen',
  u'state': u'NH',
  u'title': u'2014 New Hampshire Senate: Brown vs. Shaheen',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-new-hampshire-senate-brown-vs-shaheen'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Capito',
    u'first_name': u'Shelley',
    u'incumbent': False,
    u'last_name': u'Moore Capito',
    u'lead_confidence': 100.0,
    u'party': u'Rep',
    u'value': 53.5},
   {u'choice': u'Tennant',
    u'first_name': u'Natalie',
    u'incumbent': False,
    u'last_name': u'Tennant',
    u'lead_confidence': 0.0,
    u'party': u'Dem',
    u'value': 35.8}],
  u'last_updated': u'2014-10-26T15:04:28.000Z',
  u'poll_count': 14,
  u'short_title': u'2014 West Virginia Senate',
  u'slug': u'2014-west-virginia-senate-capito-vs-tennant',
  u'state': u'WV',
  u'title': u'2014 West Virginia Senate: Capito vs. Tennant',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-west-virginia-senate-capito-vs-tennant'},
 {u'election_date': u'2014-11-04',
  u'estimates': [],
  u'last_updated': u'2013-10-28T17:33:36.000Z',
  u'poll_count': 3,
  u'short_title': u'NH Senate: Bass vs. Shaheen',
  u'slug': u'2014-new-hampshire-senate-bass-vs-shaheen',
  u'state': u'NH',
  u'title': u'2014 New Hampshire Senate: Bass vs. Shaheen',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-new-hampshire-senate-bass-vs-shaheen'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Hagan',
    u'first_name': u'Kay',
    u'incumbent': True,
    u'last_name': u'Hagan',
    u'lead_confidence': 69.7,
    u'party': u'Dem',
    u'value': 46.3},
   {u'choice': u'Tillis',
    u'first_name': u'Thom',
    u'incumbent': False,
    u'last_name': u'Tillis',
    u'lead_confidence': 30.3,
    u'party': u'Rep',
    u'value': 45.7},
   {u'choice': u'Haugh',
    u'first_name': u'Sean',
    u'incumbent': False,
    u'last_name': u'Haugh',
    u'lead_confidence': None,
    u'party': u'Lib',
    u'value': 4.9}],
  u'last_updated': u'2014-11-03T23:42:00.000Z',
  u'poll_count': 76,
  u'short_title': u'2014 North Carolina Senate',
  u'slug': u'2014-north-carolina-senate-tillis-vs-hagan',
  u'state': u'NC',
  u'title': u'2014 North Carolina Senate: Tillis vs. Hagan',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-north-carolina-senate-tillis-vs-hagan'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Warner',
    u'first_name': u'Mark',
    u'incumbent': True,
    u'last_name': u'Warner',
    u'lead_confidence': 99.9,
    u'party': u'Dem',
    u'value': 50.3},
   {u'choice': u'Gillespie',
    u'first_name': u'Ed',
    u'incumbent': False,
    u'last_name': u'Gillespie',
    u'lead_confidence': 0.0,
    u'party': u'Rep',
    u'value': 38.7}],
  u'last_updated': u'2014-10-31T11:03:15.000Z',
  u'poll_count': 22,
  u'short_title': u'2014 Virginia Senate',
  u'slug': u'2014-virginia-senate-gillespie-vs-warner',
  u'state': u'VA',
  u'title': u'2014 Virginia Senate: Gillespie vs. Warner',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-virginia-senate-gillespie-vs-warner'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Gardner',
    u'first_name': u'Cory',
    u'incumbent': False,
    u'last_name': u'Gardner',
    u'lead_confidence': 93.2,
    u'party': u'Rep',
    u'value': 49.2},
   {u'choice': u'Udall',
    u'first_name': u'Mark',
    u'incumbent': True,
    u'last_name': u'Udall',
    u'lead_confidence': 6.8,
    u'party': u'Dem',
    u'value': 47.3}],
  u'last_updated': u'2014-11-03T13:50:32.000Z',
  u'poll_count': 54,
  u'short_title': u'2014 Colorado Senate',
  u'slug': u'2014-colorado-senate-gardner-vs-udall',
  u'state': u'CO',
  u'title': u'2014 Colorado Senate: Gardner vs. Udall',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-colorado-senate-gardner-vs-udall'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Durbin',
    u'first_name': u'Dick',
    u'incumbent': True,
    u'last_name': u'Durbin',
    u'lead_confidence': 100.0,
    u'party': u'Dem',
    u'value': 51.6},
   {u'choice': u'Oberweis',
    u'first_name': u'Jim',
    u'incumbent': False,
    u'last_name': u'Oberweis',
    u'lead_confidence': 0.0,
    u'party': u'Rep',
    u'value': 38.7},
   {u'choice': u'Other',
    u'first_name': None,
    u'incumbent': None,
    u'last_name': None,
    u'lead_confidence': None,
    u'party': None,
    u'value': 3.1}],
  u'last_updated': u'2014-11-03T02:40:53.000Z',
  u'poll_count': 15,
  u'short_title': u'IL Senate: Oberweis vs. Durbin',
  u'slug': u'2014-illinois-senate-oberweis-vs-durbin',
  u'state': u'IL',
  u'title': u'2014 Illinois Senate: Oberweis vs. Durbin',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-illinois-senate-oberweis-vs-durbin'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Sullivan',
    u'first_name': u'Dan',
    u'incumbent': False,
    u'last_name': u'Sullivan',
    u'lead_confidence': 99.8,
    u'party': u'Rep',
    u'value': 50.0},
   {u'choice': u'Begich',
    u'first_name': u'Mark',
    u'incumbent': True,
    u'last_name': u'Begich',
    u'lead_confidence': 0.2,
    u'party': u'Dem',
    u'value': 45.7}],
  u'last_updated': u'2014-11-04T03:16:32.000Z',
  u'poll_count': 35,
  u'short_title': u'2014 Alaska Senate: Sullivan vs. Begich',
  u'slug': u'2014-alaska-senate-sullivan-vs-begich',
  u'state': u'AK',
  u'title': u'2014 Alaska Senate: Sullivan vs. Begich',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-alaska-senate-sullivan-vs-begich'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Ernst',
    u'first_name': u'Joni',
    u'incumbent': False,
    u'last_name': u'Ernst',
    u'lead_confidence': 94.1,
    u'party': u'Rep',
    u'value': 48.1},
   {u'choice': u'Braley',
    u'first_name': u'Bruce',
    u'incumbent': False,
    u'last_name': u'Braley',
    u'lead_confidence': 5.9,
    u'party': u'Dem',
    u'value': 45.6}],
  u'last_updated': u'2014-11-03T23:48:30.000Z',
  u'poll_count': 55,
  u'short_title': u'2014 Iowa Senate',
  u'slug': u'2014-iowa-senate-ernst-vs-braley',
  u'state': u'IA',
  u'title': u'2014 Iowa Senate: Ernst vs. Braley',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-iowa-senate-ernst-vs-braley'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Cochran',
    u'first_name': u'Thad',
    u'incumbent': True,
    u'last_name': u'Cochran',
    u'lead_confidence': 99.9,
    u'party': u'Rep',
    u'value': 44.2},
   {u'choice': u'Childers',
    u'first_name': u'Travis',
    u'incumbent': False,
    u'last_name': u'Childers',
    u'lead_confidence': 0.0,
    u'party': u'Dem',
    u'value': 26.7},
   {u'choice': u'Other',
    u'first_name': None,
    u'incumbent': None,
    u'last_name': None,
    u'lead_confidence': None,
    u'party': None,
    u'value': 9.0}],
  u'last_updated': u'2014-10-26T15:11:17.000Z',
  u'poll_count': 8,
  u'short_title': u'2014 Mississippi Senate',
  u'slug': u'2014-mississippi-senate-cochran-vs-childers',
  u'state': u'MS',
  u'title': u'2014 Mississippi Senate: Cochran vs. Childers',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-mississippi-senate-cochran-vs-childers'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Merkley',
    u'first_name': u'Jeff',
    u'incumbent': True,
    u'last_name': u'Merkley',
    u'lead_confidence': 100.0,
    u'party': u'Dem',
    u'value': 52.7},
   {u'choice': u'Wehby',
    u'first_name': u'Monica',
    u'incumbent': False,
    u'last_name': u'Wehby',
    u'lead_confidence': 0.0,
    u'party': u'Rep',
    u'value': 35.2}],
  u'last_updated': u'2014-10-31T11:30:22.000Z',
  u'poll_count': 19,
  u'short_title': u'2014 Oregon Senate',
  u'slug': u'2014-oregon-senate-wehby-vs-merkley',
  u'state': u'OR',
  u'title': u'2014 Oregon Senate: Wehby vs. Merkley',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-oregon-senate-wehby-vs-merkley'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Perdue',
    u'first_name': u'David',
    u'incumbent': False,
    u'last_name': u'Perdue',
    u'lead_confidence': 99.9,
    u'party': u'Rep',
    u'value': 47.4},
   {u'choice': u'Nunn',
    u'first_name': u'Michelle',
    u'incumbent': False,
    u'last_name': u'Nunn',
    u'lead_confidence': 0.0,
    u'party': u'Dem',
    u'value': 43.4},
   {u'choice': u'Swafford',
    u'first_name': u'Amanda',
    u'incumbent': False,
    u'last_name': u'Swafford',
    u'lead_confidence': None,
    u'party': u'Lib',
    u'value': 3.7}],
  u'last_updated': u'2014-11-04T00:18:59.000Z',
  u'poll_count': 51,
  u'short_title': u'2014 Georgia Senate',
  u'slug': u'2014-georgia-senate-perdue-vs-nunn',
  u'state': u'GA',
  u'title': u'2014 Georgia Senate: Perdue vs. Nunn',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-georgia-senate-perdue-vs-nunn'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Sasse',
    u'first_name': u'Ben',
    u'incumbent': False,
    u'last_name': u'Sasse',
    u'lead_confidence': 100.0,
    u'party': u'Rep',
    u'value': 57.2},
   {u'choice': u'Domina',
    u'first_name': u'David',
    u'incumbent': False,
    u'last_name': u'Domina',
    u'lead_confidence': 0.0,
    u'party': u'Dem',
    u'value': 30.3}],
  u'last_updated': u'2014-10-26T15:13:42.000Z',
  u'poll_count': 6,
  u'short_title': u'2014 Nebraska Senate: Sasse vs. Domina',
  u'slug': u'2014-nebraska-senate-sasse-vs-domina',
  u'state': u'NE',
  u'title': u'2014 Nebraska Senate: Sasse vs. Domina',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-nebraska-senate-sasse-vs-domina'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Rounds',
    u'first_name': u'Mike',
    u'incumbent': False,
    u'last_name': u'Rounds',
    u'lead_confidence': 99.9,
    u'party': u'Rep',
    u'value': 43.4},
   {u'choice': u'Weiland',
    u'first_name': u'Rick',
    u'incumbent': False,
    u'last_name': u'Weiland',
    u'lead_confidence': 0.0,
    u'party': u'Dem',
    u'value': 29.7},
   {u'choice': u'Pressler',
    u'first_name': u'Larry',
    u'incumbent': False,
    u'last_name': u'Pressler',
    u'lead_confidence': None,
    u'party': u'Ind',
    u'value': 17.7},
   {u'choice': u'Other',
    u'first_name': None,
    u'incumbent': None,
    u'last_name': None,
    u'lead_confidence': None,
    u'party': None,
    u'value': 1.7}],
  u'last_updated': u'2014-10-30T11:51:11.000Z',
  u'poll_count': 25,
  u'short_title': u'2014 South Dakota Senate',
  u'slug': u'2014-south-dakota-senate-rounds-vs-weiland',
  u'state': u'SD',
  u'title': u'2014 South Dakota Senate: Rounds vs. Weiland',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-south-dakota-senate-rounds-vs-weiland'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Collins',
    u'first_name': u'Susan',
    u'incumbent': True,
    u'last_name': u'Collins',
    u'lead_confidence': 100.0,
    u'party': u'Rep',
    u'value': 61.1},
   {u'choice': u'Bellows',
    u'first_name': u'Shenna',
    u'incumbent': False,
    u'last_name': u'Bellows',
    u'lead_confidence': 0.0,
    u'party': u'Dem',
    u'value': 34.1},
   {u'choice': u'Other',
    u'first_name': None,
    u'incumbent': None,
    u'last_name': None,
    u'lead_confidence': None,
    u'party': None,
    u'value': 1.5}],
  u'last_updated': u'2014-11-03T19:11:54.000Z',
  u'poll_count': 16,
  u'short_title': u'2014 Maine Senate',
  u'slug': u'2014-maine-senate-collins-vs-bellows',
  u'state': u'ME',
  u'title': u'2014 Maine Senate: Collins vs. Bellows',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-maine-senate-collins-vs-bellows'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Franken',
    u'first_name': u'Al',
    u'incumbent': True,
    u'last_name': u'Franken',
    u'lead_confidence': 100.0,
    u'party': u'Dem',
    u'value': 51.5},
   {u'choice': u'McFadden',
    u'first_name': u'Mike',
    u'incumbent': False,
    u'last_name': u'McFadden',
    u'lead_confidence': 0.0,
    u'party': u'Rep',
    u'value': 39.9}],
  u'last_updated': u'2014-11-04T03:13:27.000Z',
  u'poll_count': 21,
  u'short_title': u'2014 Minnesota Senate',
  u'slug': u'2014-minnesota-senate-mcfadden-vs-franken',
  u'state': u'MN',
  u'title': u'2014 Minnesota Senate: McFadden vs. Franken',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-minnesota-senate-mcfadden-vs-franken'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Cornyn',
    u'first_name': u'John',
    u'incumbent': True,
    u'last_name': u'Cornyn',
    u'lead_confidence': 100.0,
    u'party': u'Rep',
    u'value': 54.0},
   {u'choice': u'Alameel',
    u'first_name': u'David',
    u'incumbent': False,
    u'last_name': u'Alameel',
    u'lead_confidence': 0.0,
    u'party': u'Dem',
    u'value': 30.9},
   {u'choice': u'Other',
    u'first_name': None,
    u'incumbent': None,
    u'last_name': None,
    u'lead_confidence': None,
    u'party': None,
    u'value': 0.8}],
  u'last_updated': u'2014-10-26T15:27:24.000Z',
  u'poll_count': 10,
  u'short_title': u'2014 Texas Senate',
  u'slug': u'2014-texas-senate-cornyn-vs-alameel',
  u'state': u'TX',
  u'title': u'2014 Texas Senate: Cornyn vs. Alameel',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-texas-senate-cornyn-vs-alameel'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Graham',
    u'first_name': u'Lindsey',
    u'incumbent': True,
    u'last_name': u'Graham',
    u'lead_confidence': 99.9,
    u'party': u'Rep',
    u'value': 47.6},
   {u'choice': u'Hutto',
    u'first_name': u'Brad',
    u'incumbent': False,
    u'last_name': u'Hutto',
    u'lead_confidence': 0.0,
    u'party': u'Dem',
    u'value': 29.5},
   {u'choice': u'Other',
    u'first_name': None,
    u'incumbent': None,
    u'last_name': None,
    u'lead_confidence': None,
    u'party': None,
    u'value': 10.0}],
  u'last_updated': u'2014-10-26T15:25:34.000Z',
  u'poll_count': 8,
  u'short_title': u'2014 South Carolina Senate: Graham vs. Hutto',
  u'slug': u'2014-south-carolina-senate-graham-vs-hutto',
  u'state': u'SC',
  u'title': u'2014 South Carolina Senate: Graham vs. Hutto',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-south-carolina-senate-graham-vs-hutto'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Scott',
    u'first_name': u'Tim',
    u'incumbent': True,
    u'last_name': u'Scott',
    u'lead_confidence': 100.0,
    u'party': u'Rep',
    u'value': 55.1},
   {u'choice': u'Dickerson',
    u'first_name': u'Joyce',
    u'incumbent': False,
    u'last_name': u'Dickerson',
    u'lead_confidence': 0.0,
    u'party': u'Dem',
    u'value': 27.5}],
  u'last_updated': u'2014-10-26T15:25:34.000Z',
  u'poll_count': 6,
  u'short_title': u'2014 South Carolina Senate: Scott vs. Dickerson',
  u'slug': u'2014-south-carolina-senate-scott-vs-dickerson',
  u'state': u'SC',
  u'title': u'2014 South Carolina Senate: Scott vs. Dickerson',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-south-carolina-senate-scott-vs-dickerson'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Inhofe',
    u'first_name': u'Jim',
    u'incumbent': True,
    u'last_name': u'Inhofe',
    u'lead_confidence': 100.0,
    u'party': u'Rep',
    u'value': 64.4},
   {u'choice': u'Silverstein',
    u'first_name': u'Matt',
    u'incumbent': False,
    u'last_name': u'Silverstein',
    u'lead_confidence': 0.0,
    u'party': u'Dem',
    u'value': 27.1},
   {u'choice': u'Other',
    u'first_name': None,
    u'incumbent': None,
    u'last_name': None,
    u'lead_confidence': None,
    u'party': None,
    u'value': 2.8}],
  u'last_updated': u'2014-11-04T02:52:48.000Z',
  u'poll_count': 8,
  u'short_title': u'2014 Oklahoma Senate: Inhofe vs. Silverstein',
  u'slug': u'2014-oklahoma-senate-inhofe-vs-silverstein',
  u'state': u'OK',
  u'title': u'2014 Oklahoma Senate: Inhofe vs. Silverstein',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-oklahoma-senate-inhofe-vs-silverstein'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Udall',
    u'first_name': u'Tom',
    u'incumbent': True,
    u'last_name': u'Udall',
    u'lead_confidence': 99.9,
    u'party': u'Dem',
    u'value': 52.1},
   {u'choice': u'Weh',
    u'first_name': u'Allen',
    u'incumbent': False,
    u'last_name': u'Weh',
    u'lead_confidence': 0.1,
    u'party': u'Rep',
    u'value': 39.6},
   {u'choice': u'Other',
    u'first_name': None,
    u'incumbent': None,
    u'last_name': None,
    u'lead_confidence': None,
    u'party': None,
    u'value': 1.0}],
  u'last_updated': u'2014-10-28T22:38:56.000Z',
  u'poll_count': 12,
  u'short_title': u'2014 New Mexico Senate',
  u'slug': u'2014-new-mexico-senate-weh-vs-udall',
  u'state': u'NM',
  u'title': u'2014 New Mexico Senate: Weh vs. Udall',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-new-mexico-senate-weh-vs-udall'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Booker',
    u'first_name': u'Cory',
    u'incumbent': True,
    u'last_name': u'Booker',
    u'lead_confidence': 100.0,
    u'party': u'Dem',
    u'value': 52.7},
   {u'choice': u'Bell',
    u'first_name': u'Jeff',
    u'incumbent': False,
    u'last_name': u'Bell',
    u'lead_confidence': 0.0,
    u'party': u'Rep',
    u'value': 37.4},
   {u'choice': u'Other',
    u'first_name': None,
    u'incumbent': None,
    u'last_name': None,
    u'lead_confidence': None,
    u'party': None,
    u'value': 0.8}],
  u'last_updated': u'2014-11-03T20:01:54.000Z',
  u'poll_count': 15,
  u'short_title': u'2014 New Jersey Senate',
  u'slug': u'2014-new-jersey-senate-bell-vs-booker',
  u'state': u'NJ',
  u'title': u'2014 New Jersey Senate: Bell vs. Booker',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-new-jersey-senate-bell-vs-booker'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Risch',
    u'first_name': u'Jim',
    u'incumbent': True,
    u'last_name': u'Risch',
    u'lead_confidence': 100.0,
    u'party': u'Rep',
    u'value': 57.7},
   {u'choice': u'Mitchell',
    u'first_name': u'Nels',
    u'incumbent': False,
    u'last_name': u'Mitchell',
    u'lead_confidence': 0.0,
    u'party': u'Dem',
    u'value': 29.2}],
  u'last_updated': u'2014-10-26T14:58:06.000Z',
  u'poll_count': 6,
  u'short_title': u'2014 Idaho Senate',
  u'slug': u'2014-idaho-senate-risch-vs-mitchell',
  u'state': u'ID',
  u'title': u'2014 Idaho Senate: Risch vs. Mitchell',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-idaho-senate-risch-vs-mitchell'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Alexander',
    u'first_name': u'Lamar',
    u'incumbent': True,
    u'last_name': u'Alexander',
    u'lead_confidence': 100.0,
    u'party': u'Rep',
    u'value': 55.3},
   {u'choice': u'Ball',
    u'first_name': u'Gordon',
    u'incumbent': False,
    u'last_name': u'Ball',
    u'lead_confidence': 0.0,
    u'party': u'Dem',
    u'value': 32.5},
   {u'choice': u'Other',
    u'first_name': None,
    u'incumbent': None,
    u'last_name': None,
    u'lead_confidence': None,
    u'party': None,
    u'value': 1.2}],
  u'last_updated': u'2014-10-26T15:26:32.000Z',
  u'poll_count': 6,
  u'short_title': u'2014 Tennessee Senate',
  u'slug': u'2014-tennessee-senate-alexander-vs-ball',
  u'state': u'TN',
  u'title': u'2014 Tennessee Senate: Alexander vs. Ball',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-tennessee-senate-alexander-vs-ball'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Enzi',
    u'first_name': u'Mike',
    u'incumbent': True,
    u'last_name': u'Enzi',
    u'lead_confidence': 100.0,
    u'party': u'Rep',
    u'value': 68.9},
   {u'choice': u'Hardy',
    u'first_name': u'Charlie',
    u'incumbent': False,
    u'last_name': u'Hardy',
    u'lead_confidence': 0.0,
    u'party': u'Dem',
    u'value': 25.5}],
  u'last_updated': u'2014-10-26T15:00:29.000Z',
  u'poll_count': 5,
  u'short_title': u'2014 Wyoming Senate',
  u'slug': u'2014-wyoming-senate',
  u'state': u'WY',
  u'title': u'2014 Wyoming Senate: Enzi vs. Hardy',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-wyoming-senate'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Roberts',
    u'first_name': u'Pat',
    u'incumbent': True,
    u'last_name': u'Roberts',
    u'lead_confidence': 74.1,
    u'party': u'Rep',
    u'value': 46.7},
   {u'choice': u'Orman',
    u'first_name': u'Greg',
    u'incumbent': False,
    u'last_name': u'Orman',
    u'lead_confidence': 25.9,
    u'party': u'ind',
    u'value': 45.0}],
  u'last_updated': u'2014-11-03T23:45:53.000Z',
  u'poll_count': 27,
  u'short_title': u'2014 Kansas Senate',
  u'slug': u'2014-kansas-senate-roberts-vs-orman-vs-taylor',
  u'state': u'KS',
  u'title': u'2014 Kansas Senate',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-kansas-senate-roberts-vs-orman-vs-taylor'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Schatz',
    u'first_name': u'Brian',
    u'incumbent': True,
    u'last_name': u'Schatz',
    u'lead_confidence': 100.0,
    u'party': u'Dem',
    u'value': 67.9},
   {u'choice': u'Cavasso',
    u'first_name': u'Campbell',
    u'incumbent': False,
    u'last_name': u'Cavasso',
    u'lead_confidence': 0.0,
    u'party': u'Rep',
    u'value': 20.2},
   {u'choice': u'Other',
    u'first_name': None,
    u'incumbent': None,
    u'last_name': None,
    u'lead_confidence': None,
    u'party': None,
    u'value': 1.0}],
  u'last_updated': u'2014-11-02T17:19:56.000Z',
  u'poll_count': 8,
  u'short_title': u'2014 Hawaii Senate',
  u'slug': u'2014-hawaii-senate-cavasso-vs-schatz',
  u'state': u'HI',
  u'title': u'2014 Hawaii Senate: Cavasso vs. Schatz',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-hawaii-senate-cavasso-vs-schatz'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Lankford',
    u'first_name': u'James',
    u'incumbent': False,
    u'last_name': u'Lankford',
    u'lead_confidence': 100.0,
    u'party': u'Rep',
    u'value': 62.4},
   {u'choice': u'Johnson',
    u'first_name': u'Connie',
    u'incumbent': False,
    u'last_name': u'Johnson',
    u'lead_confidence': 0.0,
    u'party': u'Dem',
    u'value': 28.6},
   {u'choice': u'Other',
    u'first_name': None,
    u'incumbent': None,
    u'last_name': None,
    u'lead_confidence': None,
    u'party': None,
    u'value': 2.3}],
  u'last_updated': u'2014-11-04T02:52:48.000Z',
  u'poll_count': 8,
  u'short_title': u'2014 Oklahoma Senate: Lankford vs. Johnson',
  u'slug': u'2014-oklahoma-senate-lankford-vs-johnson',
  u'state': u'OK',
  u'title': u'2014 Oklahoma Senate: Lankford vs. Johnson',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-oklahoma-senate-lankford-vs-johnson'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Daines',
    u'first_name': u'Steve',
    u'incumbent': False,
    u'last_name': u'Daines',
    u'lead_confidence': 99.9,
    u'party': u'Rep',
    u'value': 53.8},
   {u'choice': u'Curtis',
    u'first_name': u'Amanda',
    u'incumbent': False,
    u'last_name': u'Curtis',
    u'lead_confidence': 0.0,
    u'party': u'Dem',
    u'value': 36.1}],
  u'last_updated': u'2014-10-28T22:47:33.000Z',
  u'poll_count': 7,
  u'short_title': u'2014 Montana Senate: Daines vs. Curtis',
  u'slug': u'2014-montana-senate-daines-vs-curtis',
  u'state': u'MT',
  u'title': u'2014 Montana Senate: Daines vs. Curtis',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-montana-senate-daines-vs-curtis'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Reed',
    u'first_name': u'Jack',
    u'incumbent': True,
    u'last_name': u'Reed',
    u'lead_confidence': 100.0,
    u'party': u'Dem',
    u'value': 65.9},
   {u'choice': u'Zaccaria',
    u'first_name': u'Mark',
    u'incumbent': False,
    u'last_name': u'Zaccaria',
    u'lead_confidence': 0.0,
    u'party': u'Rep',
    u'value': 21.6},
   {u'choice': u'Undecided',
    u'first_name': None,
    u'incumbent': None,
    u'last_name': None,
    u'lead_confidence': None,
    u'party': None,
    u'value': 12.5}],
  u'last_updated': u'2014-10-26T15:24:13.000Z',
  u'poll_count': 4,
  u'short_title': u'2014 Rhode Island Senate: Zaccaria vs. Reed',
  u'slug': u'2014-rhode-island-senate-zaccaria-vs-reed',
  u'state': u'RI',
  u'title': u'2014 Rhode Island Senate: Zaccaria vs. Reed',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-rhode-island-senate-zaccaria-vs-reed'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Markey',
    u'first_name': u'Ed',
    u'incumbent': True,
    u'last_name': u'Markey',
    u'lead_confidence': 99.9,
    u'party': u'Dem',
    u'value': 54.1},
   {u'choice': u'Herr',
    u'first_name': u'Brian',
    u'incumbent': False,
    u'last_name': u'Herr',
    u'lead_confidence': 0.0,
    u'party': u'Rep',
    u'value': 33.4},
   {u'choice': u'Other',
    u'first_name': None,
    u'incumbent': None,
    u'last_name': None,
    u'lead_confidence': None,
    u'party': None,
    u'value': 0.2}],
  u'last_updated': u'2014-10-31T22:21:20.000Z',
  u'poll_count': 13,
  u'short_title': u'2014 Massachusetts Senate: Herr vs. Markey',
  u'slug': u'2014-massachusetts-senate-herr-vs-markey',
  u'state': u'MA',
  u'title': u'2014 Massachusetts Senate: Herr vs. Markey',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-massachusetts-senate-herr-vs-markey'},
 {u'election_date': u'2014-11-04',
  u'estimates': [{u'choice': u'Coons',
    u'first_name': u'Chris',
    u'incumbent': True,
    u'last_name': u'Coons',
    u'lead_confidence': 99.9,
    u'party': u'Dem',
    u'value': 56.0},
   {u'choice': u'Wade',
    u'first_name': u'Kevin',
    u'incumbent': False,
    u'last_name': u'Wade',
    u'lead_confidence': 0.0,
    u'party': u'Rep',
    u'value': 34.0},
   {u'choice': u'Undecided',
    u'first_name': None,
    u'incumbent': None,
    u'last_name': None,
    u'lead_confidence': None,
    u'party': None,
    u'value': 10.1}],
  u'last_updated': u'2014-10-26T14:52:36.000Z',
  u'poll_count': 5,
  u'short_title': u'2014 Delaware Senate: Wade vs. Coons',
  u'slug': u'2014-delaware-senate-wade-vs-coons',
  u'state': u'DE',
  u'title': u'2014 Delaware Senate: Wade vs. Coons',
  u'topic': u'2014-senate',
  u'url': u'http://elections.huffingtonpost.com/pollster/2014-delaware-senate-wade-vs-coons'}]
count = 0
for poll in senate_polls:
    count += 1
    print count
    _num_cand = len(poll["estimates"])

    _rep_name_first = ""
    _rep_name_last = ""
    _rep_val = 0
    _rep_lead_conf = 0
    _dem_name_first = ""
    _dem_name_last = ""
    _dem_val = 0
    _dem_lead_conf = 0
    _ind_name_first = ""
    _ind_name_last = ""
    _ind_val = 0
    _ind_lead_conf = 0
    _incumbent = ""
    
    for person in poll["estimates"]:
        if person['party'] == "Rep":
            _rep_name_first = person["first_name"]
            _rep_name_last = person["last_name"]
            _rep_val = person["value"]
            _rep_lead_conf = person["lead_confidence"]
        elif person['party'] == "Dem":
            _dem_name_first = person["first_name"]
            _dem_name_last = person["last_name"]
            _dem_val = person["value"]
            _dem_lead_conf = person["lead_confidence"]
        else:
            _ind_name_first = person["first_name"]
            _ind_name_last = person["last_name"]
            _ind_val = person["value"]
            _ind_lead_conf = person["lead_confidence"]
        if person["incumbent"] == True:
            _incumbent = person["party"]

    sen_obj = SenateStats(election_date = poll["election_date"],
                    last_updated = "logs",
                    poll_count = poll["poll_count"],
                    short_title = poll["short_title"],
                    slug = poll["slug"],
                    state = poll["state"],
                    title = poll["title"],
                    topic = poll["topic"],
                    url = poll["url"],
                    num_cand = _num_cand,
                    rep_name_first = _rep_name_first,
                    rep_name_last = _rep_name_last,
                    rep_val = _rep_val,
                    rep_lead_conf = _rep_lead_conf,
                    dem_name_first = _dem_name_first,
                    dem_name_last = _dem_name_last,
                    dem_val = _dem_val,
                    dem_lead_conf = _dem_lead_conf,
                    ind_name_first = _ind_name_first,
                    ind_name_last = _ind_name_last,
                    ind_val = _ind_val,
                    ind_lead_conf = _ind_lead_conf,
                    incumbent = _incumbent)
    try:
        sen_obj.save()
        pass
    except Exception, e:
        raise e
        print "fuck"
